Added extra events
iviteb/google-tag-manager pull request #1
Opened 2022-07-27 22:02 UTC by razvanudream

2022-08-01 09:37 UTC, claudiu-iviteb approved these changes

2022-08-01 10:06 UTC, claudiu-iviteb requested changes

2022-08-01 10:06 UTC, claudiu-iviteb commented on react/modules/extraEvents.ts
> +  observer.observe(document, {
Incearca sa folosesti un selector cat mai specific, pentru a nu asculta de toate modificarile din pagina.

2022-08-02 04:54 UTC, razvanudream commented on react/modules/extraEvents.ts
> +  observer.observe(document, {
Am reusit folosind selectorul de flex row in care e pus overlay-ul cu loginul. Ideea e ca login event-ul asta se declanseaza in interiorul eventului de userData care vine din app de login si se declanseaza la prima randare cand nu ai toate elementele in DOM. De asta am mers pe document initial, dar pare sa mearga cu acel flexRow care e si pe bocado (si voi putea instala si la ei aceeasi versiune de hkignore de la GTM). Daca vrei sa merg mai adanc de atat trebuie regandit tot flow-ul sau pus un timeout atunci cand intra pe loginEvent

2022-08-02 07:01 UTC, claudiu-iviteb approved these changes

2022-08-24 12:54 UTC, merged